name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Electronize
      run: dotnet tool install ElectronNET.CLI
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: electronize build /target win
    - name: Test
      run: dotnet test --no-restore --verbosity normal
